pub(super) struct PackageSpec {
    pub(super) name: &'static str,
    pub(super) path: &'static str,
    pub(super) phase: &'static str,
    pub(super) base_wave: i64,
    pub(super) soft: i64,
    pub(super) deps: &'static [&'static str],
    pub(super) config: &'static [&'static str],
    pub(super) group: &'static str,
}

pub(super) const PACKAGES: [PackageSpec; 8] = [
    PackageSpec {
        name: "search-source-admission",
        path: "crates/search-source/search-source-admission",
        phase: "P03",
        base_wave: 2,
        soft: 4_500,
        deps: &["search-contracts", "search-domain", "search-ports", "search-config"],
        config: &["config/sections/source_admission.md"],
        group: "A",
    },
    PackageSpec {
        name: "search-source-identity",
        path: "crates/search-source/search-source-identity",
        phase: "P03",
        base_wave: 2,
        soft: 6_500,
        deps: &["search-contracts", "search-domain"],
        config: &[],
        group: "A",
    },
    PackageSpec {
        name: "search-safe-reader",
        path: "crates/search-source/search-safe-reader",
        phase: "P03",
        base_wave: 2,
        soft: 6_500,
        deps: &["search-contracts", "search-domain", "search-ports", "search-config"],
        config: &["config/sections/source_reader.md"],
        group: "A",
    },
    PackageSpec {
        name: "search-revision-store",
        path: "crates/search-source/search-revision-store",
        phase: "P04",
        base_wave: 2,
        soft: 7_500,
        deps: &["search-contracts", "search-domain", "search-ports", "search-config"],
        config: &["config/sections/revision_store.md"],
        group: "A",
    },
    PackageSpec {
        name: "search-materializer",
        path: "crates/search-prep/search-materializer",
        phase: "P04",
        base_wave: 2,
        soft: 7_000,
        deps: &["search-contracts", "search-domain", "search-ports"],
        config: &[],
        group: "A",
    },
    PackageSpec {
        name: "search-unitizer",
        path: "crates/search-prep/search-unitizer",
        phase: "P04",
        base_wave: 2,
        soft: 6_500,
        deps: &["search-contracts", "search-domain", "search-ports"],
        config: &[],
        group: "A",
    },
    PackageSpec {
        name: "search-source-registry",
        path: "crates/search-source/search-source-registry",
        phase: "P03",
        base_wave: 2,
        soft: 6_500,
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-source-identity",
            "search-source-admission",
        ],
        config: &[],
        group: "B",
    },
    PackageSpec {
        name: "eliot-searchd",
        path: "bins/eliot-searchd",
        phase: "P04",
        base_wave: 1,
        soft: 6_500,
        deps: &[
            "eliot-searchd",
            "search-source-admission",
            "search-source-registry",
            "search-source-identity",
            "search-safe-reader",
            "search-revision-store",
            "search-materializer",
            "search-unitizer",
        ],
        config: &[],
        group: "C",
    },
];

pub(super) const CENTRAL_PACKAGES: [&str; 8] = [
    "search-source-admission",
    "search-source-registry",
    "search-source-identity",
    "search-safe-reader",
    "search-revision-store",
    "search-materializer",
    "search-unitizer",
    "eliot-searchd",
];
