//! Closed observation-root bounds.

pub use search_source_registry::{
    LEGACY_SOURCE_ROOT_CATALOG_MAX_BYTES as MAX_SOURCE_ROOT_FILE_BYTES,
    LEGACY_SOURCE_ROOT_CATALOG_MAX_ROOTS as MAX_SOURCE_ROOTS,
    MAX_SOURCE_ROOT_OBSERVATION_GAPS as MAX_OBSERVATION_GAPS,
    MAX_SOURCE_ROOT_WATCHER_HINTS as MAX_WATCHER_HINTS,
};
#[cfg(test)]
pub(crate) use search_source_registry::LEGACY_SOURCE_ROOT_CATALOG_HEADER as HEADER;

pub const MAX_SOURCE_ROOT_PATH_BYTES: usize = 512;
