pub(super) struct PackageSpec {
    pub(super) name: &'static str,
    pub(super) path: &'static str,
    pub(super) phase: &'static str,
    pub(super) soft: i64,
    pub(super) group: &'static str,
    pub(super) deps: &'static [&'static str],
    pub(super) config: &'static [&'static str],
    pub(super) qualification_sources: &'static [&'static str],
}

pub(super) const PACKAGES: [PackageSpec; 9] = [
    PackageSpec {
        name: "search-access",
        path: "crates/search-query/search-access",
        phase: "P08",
        soft: 7_500,
        group: "A",
        deps: &["search-contracts", "search-domain", "search-ports"],
        config: &[],
        qualification_sources: &[
            "qualification/query/baseline.toml",
            "qualification/query/probes.toml",
        ],
    },
    PackageSpec {
        name: "search-handles",
        path: "crates/search-query/search-handles",
        phase: "P08",
        soft: 6_500,
        group: "A",
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-config",
        ],
        config: &["config/sections/handles.md"],
        qualification_sources: &["qualification/query/probes.toml"],
    },
    PackageSpec {
        name: "search-eval",
        path: "crates/search-eval",
        phase: "P08",
        soft: 7_500,
        group: "A",
        deps: &["search-contracts", "search-domain", "search-config"],
        config: &["config/sections/observability.md"],
        qualification_sources: &[
            "qualification/query/baseline.toml",
            "qualification/query/probes.toml",
        ],
    },
    PackageSpec {
        name: "search-query-planner",
        path: "crates/search-query/search-query-planner",
        phase: "P08",
        soft: 7_500,
        group: "B",
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-config",
            "search-access",
        ],
        config: &["config/sections/query.md"],
        qualification_sources: &[
            "qualification/query/baseline.toml",
            "qualification/query/probes.toml",
        ],
    },
    PackageSpec {
        name: "search-candidate-validator",
        path: "crates/search-query/search-candidate-validator",
        phase: "P08",
        soft: 7_500,
        group: "B",
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-access",
        ],
        config: &[],
        qualification_sources: &[
            "qualification/query/baseline.toml",
            "qualification/query/probes.toml",
        ],
    },
    PackageSpec {
        name: "search-retrieval-executor",
        path: "crates/search-query/search-retrieval-executor",
        phase: "P08",
        soft: 7_500,
        group: "C",
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-config",
            "search-query-planner",
            "search-lexical",
            "search-epoch-pins",
            "search-access",
        ],
        config: &["config/sections/scheduler.md"],
        qualification_sources: &[
            "qualification/query/baseline.toml",
            "qualification/query/probes.toml",
        ],
    },
    PackageSpec {
        name: "search-result-projector",
        path: "crates/search-query/search-result-projector",
        phase: "P08",
        soft: 7_000,
        group: "C",
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-candidate-validator",
            "search-handles",
        ],
        config: &[],
        qualification_sources: &[
            "qualification/query/baseline.toml",
            "qualification/query/probes.toml",
        ],
    },
    PackageSpec {
        name: "search-continuation",
        path: "crates/search-query/search-continuation",
        phase: "P08",
        soft: 6_000,
        group: "C",
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-config",
            "search-query-planner",
            "search-access",
            "search-epoch-pins",
        ],
        config: &["config/sections/continuations.md"],
        qualification_sources: &["qualification/query/probes.toml"],
    },
    PackageSpec {
        name: "eliot-searchd",
        path: "bins/eliot-searchd",
        phase: "P08",
        soft: 6_500,
        group: "D",
        deps: &[
            "eliot-searchd",
            "search-access",
            "search-query-planner",
            "search-retrieval-executor",
            "search-candidate-validator",
            "search-handles",
            "search-result-projector",
            "search-continuation",
            "search-eval",
        ],
        config: &[],
        qualification_sources: &[
            "docs/handoff/W4_DAEMON_REENTRY.md",
            "qualification/query/baseline.toml",
            "qualification/query/probes.toml",
        ],
    },
];

pub(super) const CENTRAL_PACKAGES: [&str; 9] = [
    "search-access",
    "search-query-planner",
    "search-retrieval-executor",
    "search-candidate-validator",
    "search-handles",
    "search-result-projector",
    "search-continuation",
    "search-eval",
    "eliot-searchd",
];
