use std::path::Path;

use toml::Value;

use super::super::{Finding, load_toml, string_array};

pub(super) fn validate_toolchain(root: &Path, findings: &mut Vec<Finding>) {
    let path = root.join("rust-toolchain.toml");
    let document = match load_toml(&path) {
        Ok(document) => document,
        Err(detail) => {
            findings.push(Finding::new("TOOLCHAIN_INVALID", &path, detail));
            return;
        }
    };
    let exact = document
        .get("toolchain")
        .and_then(Value::as_table)
        .is_some_and(|toolchain| {
            toolchain.len() == 4
                && toolchain.get("channel").and_then(Value::as_str)
                    == Some("1.98.0")
                && toolchain.get("profile").and_then(Value::as_str)
                    == Some("minimal")
                && string_array(toolchain.get("components"))
                    == Some(vec!["clippy".to_owned(), "rustfmt".to_owned()])
                && string_array(toolchain.get("targets"))
                    == Some(vec!["x86_64-pc-windows-msvc".to_owned()])
        });
    if !exact {
        findings.push(Finding::new(
            "TOOLCHAIN_NOT_EXACT",
            &path,
            "toolchain must be exactly Rust 1.98.0/minimal with clippy, rustfmt and x86_64-pc-windows-msvc",
        ));
    }
}

pub(super) fn validate_cargo_config(root: &Path, findings: &mut Vec<Finding>) {
    let path = root.join(".cargo/config.toml");
    let document = match load_toml(&path) {
        Ok(document) => document,
        Err(detail) => {
            findings.push(Finding::new("CARGO_CONFIG_INVALID", &path, detail));
            return;
        }
    };
    let expected = [
        ("check-all", "check --workspace --all-targets --locked"),
        ("test-all", "test --workspace --all-targets --locked"),
        (
            "clippy-all",
            "clippy --workspace --all-targets --locked -- -D warnings",
        ),
        ("doc-all", "doc --workspace --no-deps --locked"),
    ];
    let exact = document
        .get("alias")
        .and_then(Value::as_table)
        .is_some_and(|aliases| {
            aliases.len() == expected.len()
                && expected.iter().all(|(name, command)| {
                    aliases.get(*name).and_then(Value::as_str) == Some(*command)
                })
        });
    if !exact {
        findings.push(Finding::new(
            "CARGO_ALIASES_NOT_EXACT",
            &path,
            "Cargo aliases differ from the frozen bootstrap commands",
        ));
    }
}

pub(super) fn validate_lock(
    root: &Path,
    allow_missing: bool,
    findings: &mut Vec<Finding>,
) {
    let path = root.join("Cargo.lock");
    if !path.is_file() {
        if !allow_missing {
            findings.push(Finding::new(
                "CARGO_LOCK_MISSING",
                &path,
                "verification mode requires a generated Cargo.lock",
            ));
        }
        return;
    }
    let text = match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) => {
            findings.push(Finding::new(
                "CARGO_LOCK_UNREADABLE",
                &path,
                error.to_string(),
            ));
            return;
        }
    };
    if !text.starts_with("# This file is automatically @generated by Cargo.\n")
        || !text.contains("\nversion = 4\n")
    {
        findings.push(Finding::new(
            "CARGO_LOCK_HEADER_INVALID",
            &path,
            "Cargo.lock must be Cargo-generated format version 4",
        ));
    }
}

pub(super) fn validate_workflow(root: &Path, findings: &mut Vec<Finding>) {
    let path = root.join(".github/workflows/integration-bootstrap.yml");
    let text = match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) => {
            findings.push(Finding::new(
                "BOOTSTRAP_WORKFLOW_MISSING",
                &path,
                error.to_string(),
            ));
            return;
        }
    };
    if !text.contains("workflow_dispatch:") {
        findings.push(Finding::new(
            "BOOTSTRAP_WORKFLOW_NOT_MANUAL",
            &path,
            "workflow_dispatch is required",
        ));
    }
    for trigger in [
        "push:",
        "pull_request:",
        "schedule:",
        "workflow_run:",
        "workflow_call:",
    ] {
        if text.contains(trigger) {
            findings.push(Finding::new(
                "BOOTSTRAP_WORKFLOW_AUTOMATIC_TRIGGER",
                &path,
                format!("forbidden trigger {trigger}"),
            ));
        }
    }
    if !text.contains("contents: read")
        || !text.contains("persist-credentials: false")
    {
        findings.push(Finding::new(
            "BOOTSTRAP_WORKFLOW_WRITE_CAPABLE",
            &path,
            "workflow must remain credential-free and read-only",
        ));
    }
}
