pub(super) struct PackageSpec {
    pub(super) name: &'static str,
    pub(super) path: &'static str,
    pub(super) phase: &'static str,
    pub(super) soft: i64,
    pub(super) group: &'static str,
    pub(super) deps: &'static [&'static str],
    pub(super) config: &'static [&'static str],
    pub(super) qualification_sources: &'static [&'static str],
}

pub(super) const PACKAGES: [PackageSpec; 9] = [
    PackageSpec {
        name: "search-lexical",
        path: "crates/search-lexical",
        phase: "P05",
        soft: 7_500,
        group: "A",
        deps: &["search-contracts", "search-domain", "search-ports", "search-config"],
        config: &["config/sections/lexical.md"],
        qualification_sources: &["qualification/qdrant/probes.toml"],
    },
    PackageSpec {
        name: "search-point-identity",
        path: "crates/search-index-qdrant/search-point-identity",
        phase: "P05",
        soft: 4_500,
        group: "A",
        deps: &["search-contracts", "search-domain"],
        config: &[],
        qualification_sources: &[
            "qualification/qdrant/collection-schema.toml",
            "qualification/qdrant/probes.toml",
        ],
    },
    PackageSpec {
        name: "search-qdrant-supervisor",
        path: "crates/search-index-qdrant/search-qdrant-supervisor",
        phase: "P05",
        soft: 5_500,
        group: "A",
        deps: &["search-contracts", "search-domain", "search-ports", "search-config"],
        config: &["config/sections/qdrant_process.md"],
        qualification_sources: &["qualification/qdrant/artifact.toml"],
    },
    PackageSpec {
        name: "search-qdrant-bridge",
        path: "crates/search-index-qdrant/search-qdrant-bridge",
        phase: "P05",
        soft: 7_000,
        group: "A",
        deps: &["search-contracts", "search-domain", "search-ports", "search-config"],
        config: &["config/sections/qdrant_data.md"],
        qualification_sources: &[
            "qualification/qdrant/artifact.toml",
            "qualification/qdrant/collection-schema.toml",
        ],
    },
    PackageSpec {
        name: "search-epoch-pins",
        path: "crates/search-index-qdrant/search-epoch-pins",
        phase: "P06",
        soft: 4_500,
        group: "A",
        deps: &["search-contracts", "search-domain", "search-ports"],
        config: &[],
        qualification_sources: &["qualification/qdrant/probes.toml"],
    },
    PackageSpec {
        name: "search-projection-planner",
        path: "crates/search-index-qdrant/search-projection-planner",
        phase: "P06",
        soft: 7_000,
        group: "B",
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-point-identity",
        ],
        config: &[],
        qualification_sources: &[
            "qualification/qdrant/collection-schema.toml",
            "qualification/qdrant/probes.toml",
        ],
    },
    PackageSpec {
        name: "search-index-reclaimer",
        path: "crates/search-index-qdrant/search-index-reclaimer",
        phase: "P07",
        soft: 4_500,
        group: "B",
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-config",
            "search-epoch-pins",
        ],
        config: &["config/sections/index_reclaim.md"],
        qualification_sources: &["qualification/qdrant/probes.toml"],
    },
    PackageSpec {
        name: "search-publication",
        path: "crates/search-index-qdrant/search-publication",
        phase: "P07",
        soft: 7_500,
        group: "C",
        deps: &[
            "search-contracts",
            "search-domain",
            "search-ports",
            "search-projection-planner",
            "search-point-identity",
        ],
        config: &[],
        qualification_sources: &[
            "qualification/qdrant/collection-schema.toml",
            "qualification/qdrant/probes.toml",
        ],
    },
    PackageSpec {
        name: "eliot-searchd",
        path: "bins/eliot-searchd",
        phase: "P07",
        soft: 6_500,
        group: "D",
        deps: &[
            "eliot-searchd",
            "search-lexical",
            "search-projection-planner",
            "search-point-identity",
            "search-qdrant-supervisor",
            "search-qdrant-bridge",
            "search-publication",
            "search-epoch-pins",
            "search-index-reclaimer",
        ],
        config: &[],
        qualification_sources: &[
            "docs/handoff/W3_DAEMON_REENTRY.md",
            "qualification/qdrant/artifact.toml",
            "qualification/qdrant/collection-schema.toml",
        ],
    },
];

pub(super) const CENTRAL_PACKAGES: [&str; 9] = [
    "search-lexical",
    "search-projection-planner",
    "search-point-identity",
    "search-qdrant-supervisor",
    "search-qdrant-bridge",
    "search-publication",
    "search-epoch-pins",
    "search-index-reclaimer",
    "eliot-searchd",
];
